////////////////////////////////////////////////////////////////////////////////
//
// Filename:	../demo-out/regdefs.cpp
//
// Project:	AutoFPGA, a utility for composing FPGA designs from peripherals
// {{{
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	./autofpga -d -o ../demo-out -I ../auto-data allclocks.txt bkram.txt buserr.txt clkcheck.txt crossbus.txt ddr3.txt edidslvscope.txt edid.txt exconsole.txt flashcfg.txt flash.txt global.txt gpio.txt gps.txt hdmi.txt i2ccpu.txt i2cdma.txt i2saudio.txt icape.txt meganet.txt mdio.txt pic.txt pwrcount.txt rtcdate.txt rtcgps.txt spio.txt sdio.txt vadj33.txt version.txt wboledbw.txt wbpmic.txt wbuarbiter.txt wbubus.txt zipcpu.txt zipmaster.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2017-2024, Gisselquist Technology, LLC
// {{{
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
// }}}
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <ctype.h>
#include "regdefs.h"

const	REGNAME	raw_bregs[] = {
	{ R_SDIO_CTRL       ,	"SDCARD"          	},
	{ R_SDIO_DATA       ,	"SDDATA"          	},
	{ R_SDIO_FIFOA      ,	"SDFIFOA"         	},
	{ R_SDIO_FIFOA      ,	"SDFIF0"          	},
	{ R_SDIO_FIFOA      ,	"SDFIFA"          	},
	{ R_SDIO_FIFOB      ,	"SDFIFOB"         	},
	{ R_SDIO_FIFOB      ,	"SDFIF1"          	},
	{ R_SDIO_FIFOB      ,	"SDFIFB"          	},
	{ R_SDIO_PHY        ,	"SDPHY"           	},
	{ R_FLASH           ,	"FLASH"           	},
	{ R_FLASHCFG        ,	"FLASHCFG"        	},
	{ R_FLASHCFG        ,	"QSPIC"           	},
	{ R_EDIDSLVSCOPE    ,	"EDIDSLVSCOPE"    	},
	{ R_EDIDSLVSCOPED   ,	"EDIDSLVSCOPED"   	},
	{ R_MIC_DATA        ,	"MICD"            	},
	{ R_MIC_CTRL        ,	"MICC"            	},
	{ R_GPSU_SETUP      ,	"GPSSETUP"        	},
	{ R_GPSU_FIFO       ,	"GPSFIFO"         	},
	{ R_GPSU_UARTRX     ,	"GPSRX"           	},
	{ R_GPSU_UARTTX     ,	"GPSTX"           	},
	{ R_CFG_CRC         ,	"FPGACRC"         	},
	{ R_CFG_FAR         ,	"FPGAFAR"         	},
	{ R_CFG_FDRI        ,	"FPGAFDRI"        	},
	{ R_CFG_FDRO        ,	"FPGAFDRO"        	},
	{ R_CFG_CMD         ,	"FPGACMD"         	},
	{ R_CFG_CTL0        ,	"FPGACTL0"        	},
	{ R_CFG_MASK        ,	"FPGAMASK"        	},
	{ R_CFG_STAT        ,	"FPGASTAT"        	},
	{ R_CFG_LOUT        ,	"FPGALOUT"        	},
	{ R_CFG_COR0        ,	"FPGACOR0"        	},
	{ R_CFG_MFWR        ,	"FPGAMFWR"        	},
	{ R_CFG_CBC         ,	"FPGACBC"         	},
	{ R_CFG_IDCODE      ,	"FPGAIDCODE"      	},
	{ R_CFG_AXSS        ,	"FPGAAXSS"        	},
	{ R_CFG_COR1        ,	"FPGACOR1"        	},
	{ R_CFG_WBSTAR      ,	"WBSTAR"          	},
	{ R_CFG_TIMER       ,	"CFGTIMER"        	},
	{ R_CFG_BOOTSTS     ,	"BOOTSTS"         	},
	{ R_CFG_CTL1        ,	"FPGACTL1"        	},
	{ R_CFG_BSPI        ,	"FPGABSPI"        	},
	{ R_MEGANET_RXCMD   ,	"MEGANETRX"       	},
	{ R_MEGANET_TXCMD   ,	"MEGANETTX"       	},
	{ R_MEGANET_MACHI   ,	"MEGANETMACHI"    	},
	{ R_MEGANET_MACLO   ,	"MEGANETMACLO"    	},
	{ R_MEGANET_IPADDR  ,	"MEGANETIPADDR"   	},
	{ R_MEGANET_IPADDR  ,	"MEGANETIP"       	},
	{ R_MEGANET_RXMISS  ,	"MEGANETMISS"     	},
	{ R_MEGANET_RXERR   ,	"MEGANETERR"      	},
	{ R_MEGANET_RXCRC   ,	"MEGANETCRCER"    	},
	{ R_MEGANET_DBGSEL  ,	"MEGANETDBGSL"    	},
	{ R_MEGANET_RXPKTS  ,	"MEGANETRXPKT"    	},
	{ R_MEGANET_ARPRX   ,	"MEGANETARPRX"    	},
	{ R_MEGANET_ICMPRX  ,	"MEGANETICMRX"    	},
	{ R_MEGANET_TXPKTS  ,	"MEGANETTXPKT"    	},
	{ R_MEGANET_ARPTX   ,	"MEGANETARPTX"    	},
	{ R_MEGANET_ICMPTX  ,	"MEGANETICMTX"    	},
	{ R_MEGANET_DATATX  ,	"MEGANETDATTX"    	},
	{ R_MEGANET_TXABORTS,	"MEGANETABRTS"    	},
	{ R_MEGANET_DBGRX   ,	"MEGANETDBGRX"    	},
	{ R_MEGANET_DBGTX   ,	"MEGANETDBGTX"    	},
	{ R_DDR3_PHY        ,	"DDR3_PHY"        	},
	{ R_DDR3_PHY        ,	"DPHYSTAT0"       	},
	{ R_DDR3_PHYSTAT1   ,	"DDR3_PHYSTAT1"   	},
	{ R_DDR3_PHYSTAT1   ,	"DPHYSTAT1"       	},
	{ R_DDR3_PHYSTAT2   ,	"DDR3_PHYSTAT2"   	},
	{ R_DDR3_PHYSTAT2   ,	"DPHYSTAT2"       	},
	{ R_DDR3_PHYSTAT3   ,	"DDR3_PHYSTAT3"   	},
	{ R_DDR3_PHYSTAT3   ,	"DPHYSTAT3"       	},
	{ R_DDR3_PHYCTRLSTAT,	"DDR3_PHYCTRLSTAT"	},
	{ R_DDR3_PHYCTRLSTAT,	"DCTRLSTAT"       	},
	{ R_DDR3_PHYRESET   ,	"DDR3_PHYRESET"   	},
	{ R_DDR3_PHYRESET   ,	"DCTRLRESET"      	},
	{ R_DDR3_PHYDBGSEL  ,	"DDR3_PHYDBGSEL"  	},
	{ R_DDR3_PHYDBGSEL  ,	"DCTRLDBG"        	},
	{ R_PXPLL           ,	"PXPLL"           	},
	{ R_EDID            ,	"EDID"            	},
	{ R_EDID            ,	"EDID_CTRL"       	},
	{ R_EDID            ,	"EDIDCTRL"        	},
	{ R_EDID_OVW        ,	"EDID_OVW"        	},
	{ R_EDID_OVW        ,	"EDID_OVERRIDE"   	},
	{ R_EDID_ADDR       ,	"EDID_ADDR"       	},
	{ R_EDID_ADDR       ,	"EDID_ADDRESS"    	},
	{ R_EDID_CKCOUNT    ,	"EDIDCLK"         	},
	{ R_EDID_CKCOUNT    ,	"EDID_CKCOUNT"    	},
	{ R_GPS_ALPHA       ,	"ALPHA"           	},
	{ R_GPS_BETA        ,	"BETA"            	},
	{ R_GPS_GAMMA       ,	"GAMMA"           	},
	{ R_GPS_STEP        ,	"STEP"            	},
	{ R_I2CCPU          ,	"I2CCPU"          	},
	{ R_I2CCPU          ,	"I2CCPU_CTRL"     	},
	{ R_I2CCPU          ,	"I2CCPUCTRL"      	},
	{ R_I2CCPU_OVW      ,	"I2CCPU_OVW"      	},
	{ R_I2CCPU_OVW      ,	"I2CCPU_OVERRIDE" 	},
	{ R_I2CCPU_ADDR     ,	"I2CCPU_ADDR"     	},
	{ R_I2CCPU_ADDR     ,	"I2CCPU_ADDRESS"  	},
	{ R_I2CCPU_CKCOUNT  ,	"I2CCPUCLK"       	},
	{ R_I2CCPU_CKCOUNT  ,	"I2CCPU_CKCOUNT"  	},
	{ R_I2CDMA          ,	"I2CDMA"          	},
	{ R_I2CDMA_ADDR     ,	"I2CDMAADDR"      	},
	{ R_I2CDMA_BASE     ,	"I2CDMABASE"      	},
	{ R_I2CDMA_LEN      ,	"I2CDMALEN"       	},
	{ R_OLED            ,	"OLED"            	},
	{ R_OLED_OV         ,	"OLEDOV"          	},
	{ R_OLED_ADDR       ,	"OLEDADDR"        	},
	{ R_OLED_CLK        ,	"OLEDCLK"         	},
	{ R_CLOCK           ,	"CLOCK"           	},
	{ R_TIMER           ,	"TIMER"           	},
	{ R_STOPWATCH       ,	"STOPWATCH"       	},
	{ R_CKALARM         ,	"ALARM"           	},
	{ R_CKALARM         ,	"CKALARM"         	},
	{ R_GPSTB_FREQ      ,	"GPSFREQ"         	},
	{ R_GPSTB_JUMP      ,	"GPSJUMP"         	},
	{ R_GPSTB_ERRHI     ,	"ERRHI"           	},
	{ R_GPSTB_ERRLO     ,	"ERRLO"           	},
	{ R_GPSTB_COUNTHI   ,	"CNTHI"           	},
	{ R_GPSTB_COUNTLO   ,	"CNTLO"           	},
	{ R_GPSTB_STEPHI    ,	"STEPHI"          	},
	{ R_GPSTB_STEPLO    ,	"STEPLO"          	},
	{ R_ADCCLK          ,	"ADCCLK"          	},
	{ R_BUILDTIME       ,	"BUILDTIME"       	},
	{ R_BUILDTIME       ,	"BUILDTIME"       	},
	{ R_BUSERR          ,	"BUSERR"          	},
	{ R_PIC             ,	"PIC"             	},
	{ R_GPIO            ,	"GPIO"            	},
	{ R_GPIO            ,	"GPI"             	},
	{ R_GPIO            ,	"GPO"             	},
	{ R_PWRCOUNT        ,	"PWRCOUNT"        	},
	{ R_RTCDATE         ,	"RTCDATE"         	},
	{ R_RTCDATE         ,	"DATE"            	},
	{ R_RXETH0CK        ,	"RXETH0CK"        	},
	{ R_SPIO            ,	"SPIO"            	},
	{ R_SUBSECONDS      ,	"SUBSECONDS"      	},
	{ R_TXCLK           ,	"TXCLK"           	},
	{ R_VERSION         ,	"VERSION"         	},
	{ R_EDIDRX          ,	"EDIDRX"          	},
	{ R_VIDPIPE         ,	"VIDPIPE"         	},
	{ R_VIDPIPE         ,	"VIDCTRL"         	},
	{ R_HDMIFREQ        ,	"HDMIFREQ"        	},
	{ R_SIFREQ          ,	"SIFREQ"          	},
	{ R_PXFREQ          ,	"PXFREQ"          	},
	{ R_INSIZE          ,	"INSIZE"          	},
	{ R_INPORCH         ,	"INPORCH"         	},
	{ R_INSYNC          ,	"INSYNC"          	},
	{ R_INRAW           ,	"INRAW"           	},
	{ R_HDMISIZE        ,	"HDMISIZE"        	},
	{ R_HDMIPORCH       ,	"HDMIPORCH"       	},
	{ R_HDMISYNC        ,	"HDMISYNC"        	},
	{ R_HDMIRAW         ,	"HDMIRAW"         	},
	{ R_OVADDR          ,	"OVADDR"          	},
	{ R_OVSIZE          ,	"OVSIZE"          	},
	{ R_OVOFFSET        ,	"OVOFFSET"        	},
	{ R_FPS             ,	"FPS"             	},
	{ R_CAPTURE         ,	"VCAPTURE"        	},
	{ R_CAPBASE         ,	"VCAPBASE"        	},
	{ R_CAPWORDS        ,	"VCAPWORDS"       	},
	{ R_CAPPOSN         ,	"VCAPPOSN"        	},
	{ R_CAPSIZE         ,	"VCAPSIZE"        	},
	{ R_SYNCWORD        ,	"VSYNCWORD"       	},
	{ R_CMAP            ,	"CMAP"            	},
	{ R_MDIO_BMCR       ,	"BMCR"            	},
	{ R_MDIO_BMSR       ,	"BMSR"            	},
	{ R_MDIO_PHYIDR1    ,	"PHYIDR1"         	},
	{ R_MDIO_PHYIDR2    ,	"PHYIDR2"         	},
	{ R_MDIO_ANAR       ,	"ANAR"            	},
	{ R_MDIO_ANLPAR     ,	"ANLPAR"          	},
	{ R_MDIO_ANER       ,	"ANER"            	},
	{ R_MDIO_ANNPTR     ,	"ANNPTR"          	},
	{ R_MDIO_ANNPRR     ,	"ANNPRR"          	},
	{ R_MDIO_GBCR       ,	"GBCR"            	},
	{ R_MDIO_GBSR       ,	"GBSR"            	},
	{ R_MDIO_MACR       ,	"MACR"            	},
	{ R_MDIO_MAADR      ,	"MAADR"           	},
	{ R_MDIO_GBESR      ,	"GBESR"           	},
	{ R_MDIO_PHYCR      ,	"PHYCR"           	},
	{ R_MDIO_PHYSR      ,	"PHYSR"           	},
	{ R_MDIO_INER       ,	"INER"            	},
	{ R_MDIO_INSR       ,	"INSR"            	},
	{ R_MDIO_RXERC      ,	"RXERC"           	},
	{ R_MDIO_LDPSR      ,	"LDPSR"           	},
	{ R_MDIO_EPAGSR     ,	"EPAGSR"          	},
	{ R_MDIO_PAGSEL     ,	"PAGSEL"          	},
	{ R_XMDIO_PC1R      ,	"XPC1R"           	},
	{ R_XMDIO_PS1R      ,	"XPS1R"           	},
	{ R_XMDIO_EEECR     ,	"XEEECR"          	},
	{ R_XMDIO_EEEWER    ,	"XEEEWER"         	},
	{ R_XMDIO_EEEAR     ,	"XEEEAR"          	},
	{ R_XMDIO_EEELPAR   ,	"XEEELPAR"        	},
	{ R_XMDIO_LACR      ,	"XLACR"           	},
	{ R_XMDIO_LCR       ,	"XLCR"            	},
	{ R_BKRAM           ,	"RAM"             	},
	{ R_SDRAM           ,	"SDRAM"           	},
	{ R_ZIPCTRL         ,	"CPU"             	},
	{ R_ZIPCTRL         ,	"ZIPCTRL"         	},
	{ R_ZIPREGS         ,	"ZIPREGS"         	},
	{ R_ZIPS0           ,	"SR0"             	},
	{ R_ZIPS1           ,	"SR1"             	},
	{ R_ZIPS2           ,	"SR2"             	},
	{ R_ZIPS3           ,	"SR3"             	},
	{ R_ZIPS4           ,	"SR4"             	},
	{ R_ZIPS5           ,	"SR5"             	},
	{ R_ZIPS6           ,	"SR6"             	},
	{ R_ZIPS7           ,	"SR7"             	},
	{ R_ZIPS8           ,	"SR8"             	},
	{ R_ZIPS9           ,	"SR9"             	},
	{ R_ZIPS10          ,	"SR10"            	},
	{ R_ZIPS11          ,	"SR11"            	},
	{ R_ZIPS12          ,	"SR12"            	},
	{ R_ZIPSSP          ,	"SSP"             	},
	{ R_ZIPSSP          ,	"SR13"            	},
	{ R_ZIPCC           ,	"ZIPCC"           	},
	{ R_ZIPCC           ,	"CC"              	},
	{ R_ZIPCC           ,	"SCC"             	},
	{ R_ZIPCC           ,	"SR14"            	},
	{ R_ZIPPC           ,	"ZIPPC"           	},
	{ R_ZIPPC           ,	"PC"              	},
	{ R_ZIPPC           ,	"SPC"             	},
	{ R_ZIPPC           ,	"SR15"            	},
	{ R_ZIPUSER         ,	"ZIPUSER"         	},
	{ R_ZIPU0           ,	"UR0"             	},
	{ R_ZIPU1           ,	"UR1"             	},
	{ R_ZIPU2           ,	"UR2"             	},
	{ R_ZIPU3           ,	"UR3"             	},
	{ R_ZIPU4           ,	"UR4"             	},
	{ R_ZIPU5           ,	"UR5"             	},
	{ R_ZIPU6           ,	"UR6"             	},
	{ R_ZIPU7           ,	"UR7"             	},
	{ R_ZIPU8           ,	"UR8"             	},
	{ R_ZIPU9           ,	"UR9"             	},
	{ R_ZIPU10          ,	"SR10"            	},
	{ R_ZIPU11          ,	"SR11"            	},
	{ R_ZIPU12          ,	"SR12"            	},
	{ R_ZIPUSP          ,	"USP"             	},
	{ R_ZIPUSP          ,	"UR13"            	},
	{ R_ZIPUCC          ,	"ZIPUCC"          	},
	{ R_ZIPUCC          ,	"UCC"             	},
	{ R_ZIPUPC          ,	"ZIPUPC"          	},
	{ R_ZIPUPC          ,	"UPC"             	},
	{ R_ZIPSYSTEM       ,	"ZIPSYSTEM"       	},
	{ R_ZIPSYSTEM       ,	"ZIPSYS"          	},
	{ R_ZIPWATCHDOG     ,	"ZIPWATCHDOG"     	},
	{ R_ZIPBUSDOG       ,	"BUSDOG"          	},
	{ R_ZIPAPIC         ,	"ZIPAPIC"         	},
	{ R_ZIPAPIC         ,	"ALTPIC"          	},
	{ R_ZIPTIMERA       ,	"ZIPTMA"          	},
	{ R_ZIPTIMERA       ,	"ZIPTIMERA"       	},
	{ R_ZIPTIMERB       ,	"ZIPTMB"          	},
	{ R_ZIPTIMERB       ,	"ZIPTIMERB"       	},
	{ R_ZIPTIMERC       ,	"ZIPTMC"          	},
	{ R_ZIPTIMERC       ,	"ZIPTIMERC"       	},
	{ R_ZIPJIFFIES      ,	"ZIPJIFF"         	},
	{ R_ZIPMTASK        ,	"ZIPMTASK"        	},
	{ R_ZIPMSTALL       ,	"ZIPMSTALL"       	},
	{ R_ZIPMPSTAL       ,	"ZIPMPSTAL"       	},
	{ R_ZIPMINSN        ,	"ZIPMINSN"        	},
	{ R_ZIPUTASK        ,	"ZIPUTASK"        	},
	{ R_ZIPUSTALL       ,	"ZIPUSTALL"       	},
	{ R_ZIPUPSTAL       ,	"ZIPUPSTAL"       	},
	{ R_ZIPUINSN        ,	"ZIPUINSN"        	},
	{ R_ZIPUDMAC        ,	"ZIPDMAC"         	}
};

// REGSDEFS.CPP.INSERT for any bus masters
// And then from the peripherals
// And finally any master REGS.CPP.INSERT tags
#define	RAW_NREGS	(sizeof(raw_bregs)/sizeof(bregs[0]))

const	REGNAME		*bregs = raw_bregs;
const	int	NREGS = RAW_NREGS;

unsigned	addrdecode(const char *v) {
	if (isalpha(v[0])) {
		for(int i=0; i<NREGS; i++)
			if (strcasecmp(v, bregs[i].m_name)==0)
				return bregs[i].m_addr;
		fprintf(stderr, "Unknown register: %s\n", v);
		exit(-2);
	} else
		return strtoul(v, NULL, 0);
}

const	char *addrname(const unsigned v) {
	for(int i=0; i<NREGS; i++)
		if (bregs[i].m_addr == v)
			return bregs[i].m_name;
	return NULL;
}

